name: login
timestamp: 1638109023
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1637610260
positions:
  aside: Aside
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  login:
    login-4375: Login
  messages:
    system-messages-1045: 'System Messages'
  logo:
    logo-5336: 'Logo / Image'
    logo-5080: 'Logo / Image'
  menu:
    menu-3312: Menu
  social:
    social-3403: Social
  position:
    position-position-1753: Aside
  content:
    system-content-9592: 'Page Content'
  copyright:
    copyright-3434: Copyright
  horizontalmenu:
    horizontalmenu-9960: 'Horizontal Menu'
  totop:
    totop-3675: 'To Top'
  mobile-menu:
    mobile-menu-7973: Mobile-menu
inherit:
  default:
    navigation: navigation
    header: header
    intro: intro
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    expanded: expanded
    aside: aside
    mainbar: mainbar
    footer: footer
    offcanvas: offcanvas
    system-messages-1045: system-messages-7972
    logo-5336: logo-9608
    menu-3312: menu-6409
    social-3403: social-3171
    position-position-1753: position-position-4734
    system-content-9592: system-content-1587
    logo-5080: logo-9571
    copyright-3434: copyright-1736
    horizontalmenu-9960: horizontalmenu-9034
    totop-3675: totop-8670
    mobile-menu-7973: mobile-menu-5697
