name: team
timestamp: 1638109023
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1637610260
positions:
  aside: Aside
  sidebar: Sidebar
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-6463: 'System Messages'
  logo:
    logo-7417: 'Logo / Image'
    logo-7639: 'Logo / Image'
  menu:
    menu-6256: Menu
  social:
    social-5744: Social
  position:
    position-position-4144: Aside
    position-position-6323: Sidebar
  content:
    system-content-4869: 'Page Content'
  copyright:
    copyright-7937: Copyright
  horizontalmenu:
    horizontalmenu-1761: 'Horizontal Menu'
  totop:
    totop-3812: 'To Top'
  mobile-menu:
    mobile-menu-1495: Mobile-menu
inherit:
  default:
    navigation: navigation
    header: header
    intro: intro
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    expanded: expanded
    aside: aside
    mainbar: mainbar
    sidebar: sidebar
    footer: footer
    offcanvas: offcanvas
    system-messages-6463: system-messages-7972
    logo-7417: logo-9608
    menu-6256: menu-6409
    social-5744: social-3171
    position-position-4144: position-position-4734
    system-content-4869: system-content-1587
    position-position-6323: position-position-3949
    logo-7639: logo-9571
    copyright-7937: copyright-1736
    horizontalmenu-1761: horizontalmenu-9034
    totop-3812: totop-8670
    mobile-menu-1495: mobile-menu-5697
